namespace SFundR.Web.ApiModels;

// ApiModel DTOs are used by ApiController classes and are typically kept in a side-by-side folder
public class ProjectDTO : CreateProjectDTO
{
  public ProjectDTO(int id, string name, string description, List<TimeItemDTO>? items = null) : base(name, description)
  {
    Id = id;
    Items = items ?? new List<TimeItemDTO>();
  }

  public int Id { get; set; }
  public List<TimeItemDTO> Items { get; set; }
}

// Creation DTOs should not include an ID if the ID will be generated by the back end
public abstract class CreateProjectDTO
{
  protected CreateProjectDTO(string name, string description)
  {
    Name = name;
    Description = description;
  }

  public string Name { get; set; }

  public string Description { get; set; }
}
